server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

logging:
  level:
    org.springframeworkcloud.gateway: trace
    org.springframwwork.http.server.reactive: debug
    org.springframewrok.web.reactive: debug
    reactor.ipc.netty: debug

feign:
  hystrix:
    enabled: true
